# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.IP_SSH}}
        username: ${{secrets.USERNAME_SSH}}
        port: 22
        key: ${{secrets.REACT_VM_SSH}}
        
    #comment addeddi
    # - run: |
    #        cd /var/lib/actions-runner/react-project/deploy-test/deploy-test/
    #        mkdir shaaban
    #        cp -r /var/lib/actions-runner/react-project/deploy-test/deploy-test/shaaban ~/
    #        cd ~/shaaban
    #        touch mbalamula.doc
    #        cd /var/lib/actions-runner/react-project/deploy-test/deploy-test
    #        npm install
    
